# Generated by Django 5.2 on 2025-04-29 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leagueName", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailAddress", models.CharField(max_length=64)),
                ("firstName", models.CharField(max_length=32)),
                ("middleName", models.CharField(max_length=32, null=True)),
                ("lastName", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sportName", models.CharField(max_length=32)),
                ("individualSport", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.TextField(null=True)),
                (
                    "leagueID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.league",
                    ),
                ),
                (
                    "winnerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaguify.player",
                    ),
                ),
                (
                    "sportID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leaguify.sport"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Social_Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=32)),
                ("type", models.CharField(max_length=32)),
                (
                    "playerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaguify.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=32)),
                (
                    "sportID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.sport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport_Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("eLo", models.FloatField(null=True)),
                ("gamesPlayed", models.IntegerField(default=0)),
                ("winPercent", models.FloatField(default=0)),
                (
                    "leagueID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.league",
                    ),
                ),
                (
                    "sportID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leaguify.sport"
                    ),
                ),
                (
                    "teamID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gameID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.game",
                    ),
                ),
                (
                    "leagueID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.league",
                    ),
                ),
                (
                    "teamID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="teamID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leaguify.team",
            ),
        ),
        migrations.CreateModel(
            name="Team_Social_Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=32)),
                ("type", models.CharField(max_length=32)),
                (
                    "teamID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leaguify.team"
                    ),
                ),
            ],
        ),
    ]
