# Generated by Django 5.2 on 2025-04-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailAddress", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=64)),
                ("firstName", models.CharField(max_length=32)),
                ("middleName", models.CharField(max_length=32, null=True)),
                ("lastName", models.CharField(max_length=32)),
                ("last_login", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(model_name="game", name="leagueID",),
        migrations.RemoveField(model_name="game", name="sportID",),
        migrations.RemoveField(model_name="player", name="emailAddress",),
        migrations.RemoveField(model_name="player", name="firstName",),
        migrations.RemoveField(model_name="player", name="lastName",),
        migrations.RemoveField(model_name="player", name="middleName",),
        migrations.RemoveField(model_name="plays", name="leagueID",),
        migrations.RemoveField(model_name="team", name="sportID",),
        migrations.AddField(
            model_name="league",
            name="sportID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leaguify.sport",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="leagueID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="leaguify.league",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="winnerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leaguify.team"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="userID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leaguify.custom_user",
            ),
        ),
    ]
