# Generated by Django 5.2 on 2025-05-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leaguify",
            "0002_custom_user_remove_game_leagueid_remove_game_sportid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="sport_stats", name="teamID",),
        migrations.RemoveField(model_name="sport_stats", name="leagueID",),
        migrations.RemoveField(model_name="sport_stats", name="sportID",),
        migrations.AddField(
            model_name="sport_stats",
            name="additionalStats",
            field=models.BinaryField(null=True),
        ),
        migrations.CreateModel(
            name="Player_Sport_Stats",
            fields=[
                (
                    "sport_stats_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="leaguify.sport_stats",
                    ),
                ),
                (
                    "playerID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.player",
                    ),
                ),
            ],
            bases=("leaguify.sport_stats",),
        ),
        migrations.CreateModel(
            name="Team_Sport_Stats",
            fields=[
                (
                    "sport_stats_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="leaguify.sport_stats",
                    ),
                ),
                (
                    "teamID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leaguify.team",
                    ),
                ),
            ],
            bases=("leaguify.sport_stats",),
        ),
    ]
