# Generated by Django 5.2 on 2025-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguify", "0002_user_remove_game_leagueid_remove_game_sportid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="last_login", field=models.DateTimeField(null=True),
        ),
    ]
