# Generated by Django 5.2 on 2025-05-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguify", "0003_remove_sport_stats_teamid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winnerID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leaguify.team",
            ),
        ),
    ]
