# Generated by Django 5.2 on 2025-05-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguify", "0004_alter_game_winnerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statisticName", models.CharField(max_length=32)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leaguify.sport"
                    ),
                ),
            ],
        ),
    ]
