# Generated by Django 5.2 on 2025-05-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguify", "0006_alter_player_sport_stats_playerid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="teamID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leaguify.team",
            ),
        ),
    ]
